// Mocks generated by Mockito 5.4.5 from annotations
// in internlink_flutter_application/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dio/dio.dart' as _i2;
import 'package:internlink_flutter_application/core/utils/resource.dart' as _i7;
import 'package:internlink_flutter_application/features/admin/data/datasources/remote/internship_api_service.dart'
    as _i5;
import 'package:internlink_flutter_application/features/admin/data/models/request/create_internship_request.dart'
    as _i10;
import 'package:internlink_flutter_application/features/admin/data/models/request/update_internship_request.dart'
    as _i11;
import 'package:internlink_flutter_application/features/admin/data/models/response/base_response.dart'
    as _i4;
import 'package:internlink_flutter_application/features/admin/data/models/response/internship_response.dart'
    as _i3;
import 'package:internlink_flutter_application/features/admin/domain/entities/category.dart'
    as _i8;
import 'package:internlink_flutter_application/features/student/domain/entities/application.dart'
    as _i13;
import 'package:internlink_flutter_application/features/student/domain/usecases/delete_application.dart'
    as _i14;
import 'package:internlink_flutter_application/features/student/domain/usecases/get_user_application.dart'
    as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInternshipResponse_1 extends _i1.SmartFake
    implements _i3.InternshipResponse {
  _FakeInternshipResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBaseResponse_2<T> extends _i1.SmartFake
    implements _i4.BaseResponse<T> {
  _FakeBaseResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [InternshipApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockInternshipApiService extends _i1.Mock
    implements _i5.InternshipApiService {
  MockInternshipApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_0(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i2.Dio);

  @override
  _i6.Future<_i7.Resource<List<_i8.Category>>> getCategories() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [],
        ),
        returnValue: _i6.Future<_i7.Resource<List<_i8.Category>>>.value(
            _i9.dummyValue<_i7.Resource<List<_i8.Category>>>(
          this,
          Invocation.method(
            #getCategories,
            [],
          ),
        )),
      ) as _i6.Future<_i7.Resource<List<_i8.Category>>>);

  @override
  _i6.Future<_i3.InternshipResponse> createInternship(
          _i10.CreateInternshipRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createInternship,
          [request],
        ),
        returnValue:
            _i6.Future<_i3.InternshipResponse>.value(_FakeInternshipResponse_1(
          this,
          Invocation.method(
            #createInternship,
            [request],
          ),
        )),
      ) as _i6.Future<_i3.InternshipResponse>);

  @override
  _i6.Future<_i4.BaseResponse<_i3.InternshipResponse>> updateInternship(
    int? id,
    _i11.UpdateInternshipRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateInternship,
          [
            id,
            request,
          ],
        ),
        returnValue: _i6.Future<_i4.BaseResponse<_i3.InternshipResponse>>.value(
            _FakeBaseResponse_2<_i3.InternshipResponse>(
          this,
          Invocation.method(
            #updateInternship,
            [
              id,
              request,
            ],
          ),
        )),
      ) as _i6.Future<_i4.BaseResponse<_i3.InternshipResponse>>);

  @override
  _i6.Future<Map<String, dynamic>> getDropdownData() => (super.noSuchMethod(
        Invocation.method(
          #getDropdownData,
          [],
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<List<_i3.InternshipResponse>> getAllInternships() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllInternships,
          [],
        ),
        returnValue: _i6.Future<List<_i3.InternshipResponse>>.value(
            <_i3.InternshipResponse>[]),
      ) as _i6.Future<List<_i3.InternshipResponse>>);

  @override
  _i6.Future<_i3.InternshipResponse> getInternshipById(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getInternshipById,
          [id],
        ),
        returnValue:
            _i6.Future<_i3.InternshipResponse>.value(_FakeInternshipResponse_1(
          this,
          Invocation.method(
            #getInternshipById,
            [id],
          ),
        )),
      ) as _i6.Future<_i3.InternshipResponse>);

  @override
  _i6.Future<bool> deleteInternship(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteInternship,
          [id],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);
}

/// A class which mocks [GetUserApplications].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetUserApplications extends _i1.Mock
    implements _i12.GetUserApplications {
  MockGetUserApplications() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i7.Resource<List<_i13.Application>>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i6.Future<_i7.Resource<List<_i13.Application>>>.value(
            _i9.dummyValue<_i7.Resource<List<_i13.Application>>>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i6.Future<_i7.Resource<List<_i13.Application>>>);
}

/// A class which mocks [DeleteApplication].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteApplication extends _i1.Mock implements _i14.DeleteApplication {
  MockDeleteApplication() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i7.Resource<bool>> call(int? applicationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [applicationId],
        ),
        returnValue: _i6.Future<_i7.Resource<bool>>.value(
            _i9.dummyValue<_i7.Resource<bool>>(
          this,
          Invocation.method(
            #call,
            [applicationId],
          ),
        )),
      ) as _i6.Future<_i7.Resource<bool>>);
}
