// Mocks generated by Mockito 5.4.5 from annotations
// in internlink_flutter_application/test/features/profile/data/repositories/mock_profile_remote_data_source.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dio/dio.dart' as _i2;
import 'package:internlink_flutter_application/features/student/data/data_sources/remote/profile_remote_data_source.dart'
    as _i4;
import 'package:internlink_flutter_application/features/student/data/models/response/profile_dto.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProfileDto_1 extends _i1.SmartFake implements _i3.ProfileDto {
  _FakeProfileDto_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProfileRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRemoteDataSource extends _i1.Mock
    implements _i4.ProfileRemoteDataSource {
  MockProfileRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_0(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i2.Dio);

  @override
  _i5.Future<_i3.ProfileDto> getProfile() => (super.noSuchMethod(
        Invocation.method(
          #getProfile,
          [],
        ),
        returnValue: _i5.Future<_i3.ProfileDto>.value(_FakeProfileDto_1(
          this,
          Invocation.method(
            #getProfile,
            [],
          ),
        )),
      ) as _i5.Future<_i3.ProfileDto>);

  @override
  _i5.Future<_i3.ProfileDto> updateProfile(
    int? id,
    _i3.ProfileDto? dto,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [
            id,
            dto,
          ],
        ),
        returnValue: _i5.Future<_i3.ProfileDto>.value(_FakeProfileDto_1(
          this,
          Invocation.method(
            #updateProfile,
            [
              id,
              dto,
            ],
          ),
        )),
      ) as _i5.Future<_i3.ProfileDto>);

  @override
  _i5.Future<void> deleteProfile(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteProfile,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
